// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectDemo.Data;

#nullable disable

namespace projectDemo.Migrations
{
    [DbContext(typeof(EventTickDbContext))]
    partial class EventTickDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTick.Model.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatetoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaleStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CatetoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EventTick.Model.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EventTick.Model.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("EventTick.Model.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EventTick.Model.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 7, 8, 18, 48, 359, DateTimeKind.Utc).AddTicks(9321),
                            IsDeleted = false,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 7, 8, 18, 48, 359, DateTimeKind.Utc).AddTicks(9330),
                            IsDeleted = false,
                            RoleName = "ORGANIZER"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 7, 8, 18, 48, 359, DateTimeKind.Utc).AddTicks(9332),
                            IsDeleted = false,
                            RoleName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("EventTick.Model.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderDetailID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailID");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("EventTick.Model.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventID");

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("EventTick.Model.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLock")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<int?>("Isfalse")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@system.com",
                            FirstName = "admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsLock = false,
                            LastName = "admin",
                            PasswordHash = "$2a$11$RcJMFbXXFOhv5hbo4Ud8nefFW7LBQkJA/7d1nZVR.ImaGiMklfpHa",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EventTick.Model.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("EventTick.Model.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1,
                            Id = 1
                        });
                });

            modelBuilder.Entity("projectDemo.Entity.Models.ApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuncName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiLog");
                });

            modelBuilder.Entity("projectDemo.Entity.Models.Catetory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catetorys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "MUSIC"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "SPORT"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "TECHNOLOGY"
                        });
                });

            modelBuilder.Entity("projectDemo.Entity.Models.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissonsDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissonsName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            PermissonsDescription = "tạo mới user",
                            PermissonsName = "USER_CREATE"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            PermissonsDescription = "sửa user",
                            PermissonsName = "USER_UPDATE"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            PermissonsDescription = "xóa user",
                            PermissonsName = "USER_DELETE"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            PermissonsDescription = "xem user",
                            PermissonsName = "USER_VIEW"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            PermissonsDescription = "tạo role mới",
                            PermissonsName = "ROLE_CREATE"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            PermissonsDescription = " sửa role",
                            PermissonsName = "ROLE_UPDATE"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            PermissonsDescription = " xóa role",
                            PermissonsName = "ROLE_DELETE"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            PermissonsDescription = " xem role",
                            PermissonsName = "ROLE_VIEW"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            PermissonsDescription = "tạo mới event",
                            PermissonsName = "EVENT_CREATE"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            PermissonsDescription = "sửa  event",
                            PermissonsName = "EVENT_UPDATE"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            PermissonsDescription = "xóa  event",
                            PermissonsName = "EVENT_DELETE"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            PermissonsDescription = " xem event",
                            PermissonsName = "EVENT_VIEW"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            PermissonsDescription = "xem tổng vé của event",
                            PermissonsName = "EVENT_GETTOTALTICKBYID"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            PermissonsDescription = "xem tổng vé theo user",
                            PermissonsName = "EVENT_GETTOTALTICKBYUSER"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            PermissonsDescription = "tạo mới TypeTicket",
                            PermissonsName = "TYPETICKET_CREATE"
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            PermissonsDescription = "sửa  TypeTicket",
                            PermissonsName = "TYPETICKET_UPDATE"
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            PermissonsDescription = "xóa  TypeTicket",
                            PermissonsName = "TYPETICKET_DELETE"
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            PermissonsDescription = " xem TypeTicket",
                            PermissonsName = "TYPETICKET_VIEW"
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            PermissonsDescription = "xem tổng vé của TypeTicket",
                            PermissonsName = "TYPETICKET_GETROLEBYID"
                        });
                });

            modelBuilder.Entity("projectDemo.Entity.Models.RolePermissions", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18,
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EventTick.Model.Models.Event", b =>
                {
                    b.HasOne("projectDemo.Entity.Models.Catetory", "Catetory")
                        .WithMany("Events")
                        .HasForeignKey("CatetoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTick.Model.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catetory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventTick.Model.Models.Order", b =>
                {
                    b.HasOne("EventTick.Model.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventTick.Model.Models.OrderDetail", b =>
                {
                    b.HasOne("EventTick.Model.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTick.Model.Models.TicketType", "TicketTypes")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("EventTick.Model.Models.Payment", b =>
                {
                    b.HasOne("EventTick.Model.Models.Order", "Orders")
                        .WithOne("Payment")
                        .HasForeignKey("EventTick.Model.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EventTick.Model.Models.Ticket", b =>
                {
                    b.HasOne("EventTick.Model.Models.OrderDetail", "OrderDetail")
                        .WithMany("Ticket")
                        .HasForeignKey("OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("EventTick.Model.Models.TicketType", b =>
                {
                    b.HasOne("EventTick.Model.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventTick.Model.Models.UserLogin", b =>
                {
                    b.HasOne("EventTick.Model.Models.User", "user")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("EventTick.Model.Models.UserRole", b =>
                {
                    b.HasOne("EventTick.Model.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTick.Model.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projectDemo.Entity.Models.ApiLog", b =>
                {
                    b.HasOne("EventTick.Model.Models.User", "User")
                        .WithMany("ApiLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("projectDemo.Entity.Models.RolePermissions", b =>
                {
                    b.HasOne("projectDemo.Entity.Models.Permissions", "Permissions")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTick.Model.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EventTick.Model.Models.Event", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("EventTick.Model.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("EventTick.Model.Models.OrderDetail", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("EventTick.Model.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("EventTick.Model.Models.TicketType", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("EventTick.Model.Models.User", b =>
                {
                    b.Navigation("ApiLogs");

                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("projectDemo.Entity.Models.Catetory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("projectDemo.Entity.Models.Permissions", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
